import { z } from "zod"; import { documents, findProject, historicalApplications, operationFor, performanceFor, policies, projects } from "./repository"; import type { ToolName } from "./types";
const idSchema=z.object({projectId:z.string().min(1)}); const policyInput=z.object({query:z.string().min(1).optional(),ruleId:z.string().optional()});
export function queryProject(input:unknown){const {projectId}=idSchema.parse(input); const project=findProject(projectId); if(!project) return {found:false,projectId}; return {found:true,project};}
export function queryDocuments(input:unknown){const {projectId}=idSchema.parse(input); return {projectId,documents:documents.filter(d=>d.projectId===projectId)};}
export function checkMaterialCompleteness(input:unknown){const {projectId}=idSchema.parse(input); const docs=documents.filter(d=>d.projectId===projectId); const required=(policies.rules.find(r=>r.id==="P-003")?.parameters.requiredDocumentTypes as string[]) ?? []; const submitted=new Set(docs.filter(d=>d.status==="已提交").map(d=>d.type)); const missing=required.filter(t=>!submitted.has(t)); return {projectId,required,submitted:[...submitted],missing,complete:missing.length===0,policyRuleId:"P-003"};}
export function queryPolicyRules(input:unknown){const {query,ruleId}=policyInput.parse(input); const rules=policies.rules.filter(r=>ruleId?r.id===ruleId:!query||[r.id,r.title,r.description].join(" ").includes(query)); return {policyId:policies.policyId,policyName:policies.name,rules};}
export function verifyProjectData(input:unknown){const {projectId}=idSchema.parse(input); if(projectId==="PRJ-B"){const doc=documents.find(d=>d.id==="DOC-B01")!; const op=operationFor(projectId)!; const f=doc.extractedFields as Record<string,number>; const volumeDifference=(f.declaredBusinessVolume as number)-op.actualBusinessVolume; return {projectId,checks:[{metric:"运行时间",declared:f.declaredRuntimeMonths,actual:op.actualRuntimeMonths,difference:2,unit:"个月"},{metric:"累计业务量",declared:f.declaredBusinessVolume,actual:op.actualBusinessVolume,difference:volumeDifference,ratio:volumeDifference/op.actualBusinessVolume,unit:"次"},{metric:"设备利用率",declared:f.declaredUtilization,actual:op.actualUtilization,difference:(f.declaredUtilization as number)-op.actualUtilization,unit:"比例"}],risk:"存在明显数据一致性疑点"};} if(projectId==="PRJ-A"){return {projectId,checks:[{metric:"申报投资与合同",declared:2680000,actual:2180000,difference:500000,unit:"元"},{metric:"申报投资与发票",declared:2680000,actual:2160000,difference:520000,unit:"元"}],risk:"存在金额核验疑点"};} if(projectId==="PRJ-G"){return {projectId,checks:[],risk:"疑似存在同类历史申报"};} return {projectId,checks:[],risk:"未发现需提示的跨源差异"};}
export function calculateSubsidy(input:unknown){const schema=z.object({approvedInvestment:z.number().nonnegative(),rate:z.number().min(0).max(1).default(0.3),cap:z.number().nonnegative().default(500000)}); const {approvedInvestment,rate,cap}=schema.parse(input); const theoretical=approvedInvestment*rate; return {approvedInvestment,rate,theoreticalSubsidy:theoretical,finalSubsidy:Math.min(theoretical,cap),cap,policyRuleIds:["P-004","P-005"]};}
export function queryPerformance(input:unknown){const {projectId}=idSchema.parse(input); const record=performanceFor(projectId); if(!record) return {projectId,metrics:[],focus:false}; const metrics=record.metrics.map(m=>({...m,completionRate:m.target===0?0:m.actual/m.target})); return {projectId,metrics,focus:metrics.some(m=>m.completionRate<0.6),focusRuleId:"P-008"};}
export function queryRegulatoryStats(input:unknown={}){z.object({}).parse(input); const statusCounts=Object.fromEntries([...new Set(projects.map(p=>p.status))].map(s=>[s,projects.filter(p=>p.status===s).length])); const riskProjects=projects.filter(p=>p.riskLevel!=="低"); const performanceIssues=projects.filter(p=>{const pmt=performanceFor(p.id); return pmt?.metrics.some(m=>m.actual/m.target<0.6);}).map(p=>p.id); return {projectCount:projects.length,statusCounts,riskProjectIds:riskProjects.map(p=>p.id),requestedSubsidyTotal:projects.reduce((n,p)=>n+p.requestedSubsidy,0),approvedSubsidyTotal:projects.reduce((n,p)=>n+p.approvedSubsidy,0),paidSubsidyTotal:projects.reduce((n,p)=>n+p.paidSubsidy,0),pendingCount:projects.filter(p=>["待审核","待复核","待补充"].includes(p.status)).length,paidProjectsCount:projects.filter(p=>p.paidSubsidy>0).length,performanceIssueProjectIds:performanceIssues,historicalMatches:historicalApplications};}
const implementations:Record<ToolName,(input:unknown)=>unknown>={query_project:queryProject,query_documents:queryDocuments,check_material_completeness:checkMaterialCompleteness,query_policy_rules:queryPolicyRules,verify_project_data:verifyProjectData,calculate_subsidy:calculateSubsidy,query_performance:queryPerformance,query_regulatory_stats:queryRegulatoryStats};
export function executeTool(name:ToolName,input:unknown){return implementations[name](input);}
export const toolNames=Object.keys(implementations) as ToolName[];

