import { sessionContext } from '@/lib/works/finance-assistant/finance/schemas/report'; import type { AgentToolName, FinanceConversationContext } from './types';
export const financeContextSchema=sessionContext;
export const contextInputSchema=financeContextSchema.default({});
export function parseFinanceContext(value:unknown):FinanceConversationContext{return contextInputSchema.parse(value);}
export function inferIntent(message:string){if(/对账|结算|流水|一对多|多对一|多对多|金额不一致|差异|订单/.test(message))return 'reconciliation';if(/经营分析|经营报告|月报|总结.*经营|生成.*分析/.test(message))return 'report';if(/异常|关注|不正常/.test(message))return 'anomaly';if(/为什么|原因|下降.*渠道|贡献|拖累/.test(message))return 'variance';if(/同比|环比|相比|比.*月|跟.*比/.test(message))return 'comparison';return 'financial_query';}
function isFollowUp(message:string){return /^(那|跟|华东|华南|华北|支付宝|银联|微信支付|宝信|把|最大|有没有|再|这|同样|继续)/.test(message.trim())&&!/^(帮我|请|生成|给我生成)/.test(message.trim());}
function intentChanged(previous:FinanceConversationContext,message:string,nextIntent:string){return Boolean(previous.lastIntent&&previous.lastIntent!==nextIntent&&!isFollowUp(message));}
export function mergeToolContext(previous:FinanceConversationContext,message:string,toolName:AgentToolName,args:Record<string,unknown>):FinanceConversationContext{const nextIntent=inferIntent(message);const reset=intentChanged(previous,message,nextIntent);const next:FinanceConversationContext=reset?{}:{...previous,lastIntent:previous.lastIntent};const timeRange=args.timeRange as FinanceConversationContext['lastTimeRange'];const filters=(args.filters??{}) as {companyIds?:FinanceConversationContext['lastCompanyId'][];channels?:FinanceConversationContext['lastChannel'][];categories?:FinanceConversationContext['lastCategory'][]};if(timeRange)next.lastTimeRange=timeRange;if(filters.companyIds?.[0])next.lastCompanyId=filters.companyIds[0];if(filters.channels?.[0])next.lastChannel=filters.channels[0];if(filters.categories?.[0])next.lastCategory=filters.categories[0];if('metric' in args&&typeof args.metric==='string')next.lastMetric=args.metric;
  next.lastIntent=nextIntent;
  if(toolName==='reconcile_transactions'){if(!filters.companyIds?.[0])delete next.lastCompanyId;if(!filters.categories?.[0])delete next.lastCategory;if(typeof args.channel==='string')next.lastChannel=args.channel as FinanceConversationContext['lastChannel'];else if(reset)delete next.lastChannel;if(typeof args.issueType==='string')next.lastReconciliationIssueType=args.issueType as FinanceConversationContext['lastReconciliationIssueType'];else if(reset)delete next.lastReconciliationIssueType;if(typeof args.matchType==='string')next.lastReconciliationMatchType=args.matchType as FinanceConversationContext['lastReconciliationMatchType'];else if(reset)delete next.lastReconciliationMatchType;delete next.lastMetric;}
  else if(reset){delete next.lastReconciliationIssueType;delete next.lastReconciliationMatchType;}
  return parseFinanceContext(next);
}
