import { z } from 'zod';
import { financeTools } from '@/lib/works/finance-assistant/finance/tools';
import { queryInput } from '@/lib/works/finance-assistant/finance/schemas/query'; import { compareInput } from '@/lib/works/finance-assistant/finance/schemas/comparison'; import { varianceInput } from '@/lib/works/finance-assistant/finance/schemas/variance'; import { anomalyInput } from '@/lib/works/finance-assistant/finance/schemas/anomaly'; import { reconcileInput } from '@/lib/works/finance-assistant/finance/schemas/reconciliation'; import { reportInput } from '@/lib/works/finance-assistant/finance/schemas/report';
import type { AgentToolDefinition, AgentToolName } from './types';

const schemaByName:Record<AgentToolName,z.ZodType>={query_financial_data:queryInput,compare_financial_periods:compareInput,analyze_variance:varianceInput,detect_financial_anomalies:anomalyInput,reconcile_transactions:reconcileInput,generate_financial_report:reportInput};
const implementationByName:Record<AgentToolName,(input:unknown)=>unknown>={query_financial_data:financeTools.queryFinancialData,compare_financial_periods:financeTools.compareFinancialPeriods,analyze_variance:financeTools.analyzeVariance,detect_financial_anomalies:financeTools.detectFinancialAnomalies,reconcile_transactions:financeTools.reconcileTransactions,generate_financial_report:financeTools.generateFinancialReport};
const descriptions:Record<AgentToolName,string>={query_financial_data:'查询真实经营数据，支持指标、时间范围、公司/渠道/品类筛选、最多两个分组维度和占比。',compare_financial_periods:'比较两个由系统日期规则确定的期间，计算环比、同比或上一周期变化。',analyze_variance:'按公司、渠道、品类或日期分析变化贡献和集中区间。',detect_financial_anomalies:'按固定规则检测销售下降、退款率和渠道下降异常。',reconcile_transactions:'执行真实 JSON 对账，返回汇总或可追溯的对账分组及差异明细。',generate_financial_report:'编排查询、比较、变化原因和异常检测，返回经营分析事实。'};
function toParameters(schema:z.ZodType){const json=z.toJSONSchema(schema,{target:'draft-7',io:'input',unrepresentable:'any'}) as Record<string,unknown>;delete json.$schema;return json;}
export const agentToolDefinitions:AgentToolDefinition[]=(Object.keys(schemaByName) as AgentToolName[]).map(name=>({type:'function',function:{name,description:descriptions[name],parameters:toParameters(schemaByName[name])}}));
export class ToolValidationError extends Error{constructor(public readonly toolName:AgentToolName,public readonly issues:unknown){super(`Tool 参数校验失败: ${toolName}`);this.name='ToolValidationError';}}
export function executeFinanceTool(name:AgentToolName,input:unknown){const schema=schemaByName[name];if(!schema)throw new ToolValidationError(name, [{message:'未知 Tool'}]);const parsed=schema.safeParse(input);if(!parsed.success)throw new ToolValidationError(name,parsed.error.issues);return implementationByName[name](parsed.data);}
