/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import Link from "next/link"; import { useState } from "react";
import type { Project } from "@/lib/works/special-fund-supervision/types";
import type { AgentResponse } from "@/lib/works/special-fund-supervision/agent/agent";
export function Assistant({projectId}:{projectId?:string}){const [input,setInput]=useState("");const [messages,setMessages]=useState<Array<{q:string;r:AgentResponse}>>([]);const [loading,setLoading]=useState(false);async function ask(q=input){if(!q.trim())return;setInput("");setLoading(true);try{const res=await fetch("/api/experiments/special-fund-supervision/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message:q,projectId})});const r=await res.json();setMessages(m=>[...m,{q,r}]);}finally{setLoading(false);}}return <section className="sf-assistant"><div className="sf-assistant-head"><div><span className="sf-kicker">AI 监管助手</span><h2>把材料、政策和数据放在同一个判断里</h2></div><span className="sf-live">Mock Tool 已连接</span></div><div className="sf-suggestions">{(projectId==="PRJ-A"?["帮我审核这个项目","为什么暂时不能通过？","申报金额和合同金额有什么问题？"]:projectId==="PRJ-B"?["帮我检查申报数据是否真实","申报业务量和实际业务量相差多少？"]:projectId==="PRJ-C"?["这个项目拿到补贴后效果怎么样？","为什么资金已经全部使用但仍被关注？"]:["目前最值得关注的三个项目是什么？","本期一共拨付了多少专项资金？","哪个项目绩效最好？"]).map(q=><button key={q} onClick={()=>ask(q)}>{q}</button>)}</div><div className="sf-chat" aria-live="polite">{messages.length===0&&<p className="sf-empty">从一个项目开始提问，助手会展示使用的 Tool 和依据。</p>}{messages.map((m,i)=><div className="sf-message" key={i}><div className="sf-question">{m.q}</div><div className="sf-answer"><p>{m.r.answer}</p><div className="sf-tool-row">{m.r.usedTools.map(t=><span key={t}>{t}</span>)}</div>{m.r.blocks.map((b,j)=><details key={j}><summary>{b.title}</summary><pre>{JSON.stringify(b.data,null,2)}</pre></details>)}</div></div>)}</div><form onSubmit={e=>{e.preventDefault();void ask()}} className="sf-composer"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="输入你的监管问题…" aria-label="输入监管问题"/><button disabled={loading}>{loading?"查询中":"发送"}</button></form></section>}
export function Shell({children}:{children:React.ReactNode}){return <div className="sf-shell"><header className="sf-topbar"><Link href="/works/demos/special-fund-supervision" className="sf-brand"><span className="sf-brand-mark">SF</span><span><b>专项资金监管</b><small>AI Agent Demo · 虚构演示</small></span></Link><nav aria-label="监管工作台导航"><Link href="/works/demos/special-fund-supervision">工作台</Link><Link href="/works/demos/special-fund-supervision/projects">项目库</Link><Link href="/works/demos/special-fund-supervision/assistant">全局助手</Link></nav></header>{children}<footer className="sf-footer">本 Demo 中所涉及的企业、项目、政策、金额及业务数据均为虚构模拟内容，仅用于产品能力展示。</footer></div>}
export function ProjectCard({project}:{project:Project}){return <Link className="sf-project-card" href={"/works/demos/special-fund-supervision/projects/"+project.id}><div className="sf-card-top"><span>{project.id}</span><em className={"risk-"+project.riskLevel}>{project.riskLevel}关注</em></div><h3>{project.name}</h3><p>{project.companyName} · {project.region}</p><div className="sf-card-bottom"><span>{project.status}</span><strong>{project.riskTags[0]??"暂无风险提示"}</strong></div></Link>}
export function Stats({stats}:{stats:any}){return <div className="sf-stats">{[["申报项目",stats.projectCount+" 个"],["申请补贴",(stats.requestedSubsidyTotal/10000)+" 万"],["已核定",(stats.approvedSubsidyTotal/10000)+" 万"],["已拨付",(stats.paidSubsidyTotal/10000)+" 万"],["风险项目",stats.riskProjectIds.length+" 个"]].map(([label,value])=><div className="sf-stat" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>}
export function ProjectTable({projects}:{projects:Project[]}){return <div className="sf-table-wrap"><table className="sf-table"><thead><tr><th>项目</th><th>企业 / 地区</th><th>状态</th><th>风险</th><th>申请补贴</th></tr></thead><tbody>{projects.map(p=><tr key={p.id}><td><Link href={"/works/demos/special-fund-supervision/projects/"+p.id}><b>{p.id}</b> {p.name}</Link></td><td>{p.companyName} · {p.region}</td><td>{p.status}</td><td><span className={"risk-dot risk-"+p.riskLevel}>{p.riskLevel}</span></td><td>{(p.requestedSubsidy/10000).toLocaleString()} 万</td></tr>)}</tbody></table></div>}
