import { test } from "node:test";
import assert from "node:assert/strict";
import { activeInvoice, advanceJourney, createOrder, changeOrder, demoInterpret, invoiceUnavailableReason, issueInvoice, paymentLedger, quoteRefund, quoteReschedule, resolvePaidReschedule, searchTrips, shanghaiToday, startPaidReschedule, submitRefund, submitSimpleReschedule, type Order } from "../../lib/works/island-travel/domain";
import { requestSchema, responseSchema } from "../../lib/works/island-travel/schema";

const today = "2026-09-14";
const conditions = { origin: "海口", destination: "三亚", date: "2026-09-15", quantity: 1 };
const trip = searchTrips(conditions, today)[0];
test("Shanghai midnight and expired schedule boundaries", () => {
  assert.equal(shanghaiToday(new Date("2026-09-14T16:01:00Z")), "2026-09-15");
  assert.equal(searchTrips({ ...conditions, date: "2026-09-13" }, today).length, 0);
  assert.equal(searchTrips({ ...conditions, date: "2026-09-21" }, today).length, 0);
  assert.ok(searchTrips({ ...conditions, date: "2026-09-20" }, today).length);
});
test("clarify, modify, remove time preference, ordinal and unsupported", () => {
  const first = demoInterpret("从海口出发，有什么车？", {}, today);
  assert.equal(first.intent, "clarify");
  const second = demoInterpret("三亚", first.conditions, today);
  assert.equal(second.conditions.destination, "三亚");
  const third = demoInterpret("明天上午", second.conditions, today);
  assert.equal(third.intent, "search_trips");
  const fourth = demoInterpret("改成下午", third.conditions, today);
  assert.equal(fourth.conditions.date, "2026-09-15");
  assert.ok(searchTrips(fourth.conditions, today).every((t) => t.depart >= "12:00" && t.depart < "18:00"));
  assert.equal(demoInterpret("不限", fourth.conditions, today).conditions.time_preference, "不限");
  assert.equal(demoInterpret("选择第二班", fourth.conditions, today).selection, 2);
  assert.equal(demoInterpret("6人", fourth.conditions, today).intent, "unsupported");
  assert.equal(demoInterpret("退款", fourth.conditions, today).intent, "request_refund");
  assert.equal(demoInterpret("我要改签", fourth.conditions, today).intent, "request_reschedule");
  assert.equal(demoInterpret("我要开发票", fourth.conditions, today).intent, "request_invoice");
  assert.equal(demoInterpret("你好", fourth.conditions, today).intent, "unsupported");
});
test("paid reschedule preserves original ticket until success, then switches inventory and ledger once", () => {
  const original = changeOrder(createOrder([], trip, 2, "paid", true, today), "DJ-0001", "success");
  const target = searchTrips(conditions, today, original).find(t => t.depart === "13:30")!;
  const quote = quoteReschedule(original, "DJ-0001", target, today);
  assert.equal(quote.deltaCents, 2000);
  const pending = startPaidReschedule(original, quote, true, today);
  assert.equal(startPaidReschedule(pending, quote, true, today), pending);
  assert.equal(pending[0].trip.id, trip.id);
  assert.throws(() => quoteRefund(pending[0]));
  assert.throws(() => advanceJourney(pending, "DJ-0001", "boarding"));
  assert.throws(() => quoteReschedule(pending, "DJ-0001", target, today));
  assert.equal(invoiceUnavailableReason(pending[0]), "改签处理中，完成后再申请演示开票。");
  assert.throws(() => issueInvoice(pending, "DJ-0001", "personal", true));
  const unknown = resolvePaidReschedule(pending, "DJ-0001", "unknown", today).orders;
  assert.throws(() => resolvePaidReschedule(unknown, "DJ-0001", "cancel", today));
  assert.throws(() => resolvePaidReschedule(unknown, "DJ-0001", "success", today));
  const recovered = resolvePaidReschedule(unknown, "DJ-0001", "query", today);
  assert.equal(recovered.outcome, "completed");
  assert.equal(recovered.orders[0].trip.id, target.id);
  assert.equal(recovered.orders[0].amount, 276);
  assert.equal(recovered.orders[0].events.filter(e => e.type === "reschedule").length, 1);
  assert.deepEqual(paymentLedger(recovered.orders[0]), { paidCents: 27600, returnedCents: 0, netCents: 27600 });
  assert.equal(searchTrips(conditions, today, recovered.orders).find(t => t.id === trip.id)?.seats, trip.seats);
  assert.equal(searchTrips(conditions, today, recovered.orders).find(t => t.id === target.id)?.seats, target.seats - 2);
  assert.equal(resolvePaidReschedule(recovered.orders, "DJ-0001", "query", today).orders, recovered.orders);
});
test("payment failure, cancel and target shortage never partially change a ticket", () => {
  const original = changeOrder(createOrder([], trip, 1, "original", true, today), "DJ-0001", "success");
  const target = searchTrips(conditions, today, original).find(t => t.depart === "09:15")!;
  const quote = quoteReschedule(original, "DJ-0001", target, today);
  const pending = startPaidReschedule(original, quote, true, today);
  const failed = resolvePaidReschedule(pending, "DJ-0001", "failed", today);
  assert.equal(failed.outcome, "payment_failed");
  assert.equal(failed.orders[0].trip.id, trip.id);
  const cancelled = resolvePaidReschedule(failed.orders, "DJ-0001", "cancel", today).orders;
  assert.equal(cancelled[0].trip.id, trip.id);
  assert.equal(cancelled[0].reschedule, null);
  const competing = createOrder(pending, target, 3, "competing", true, today);
  assert.throws(() => resolvePaidReschedule(competing, "DJ-0001", "success", today));
  const unknown = resolvePaidReschedule(competing, "DJ-0001", "unknown", today).orders;
  const lookedUp = resolvePaidReschedule(unknown, "DJ-0001", "query", today);
  assert.equal(lookedUp.outcome, "inventory_unavailable");
  assert.equal(lookedUp.orders[0].trip.id, trip.id);
  assert.equal(lookedUp.orders[0].reschedule, null);
  assert.equal(lookedUp.orders[1].trip.id, target.id);
});
test("refund, no-price reschedule and stale quote use current fare and seats", () => {
  const expensive = searchTrips(conditions, today).find(t => t.depart === "16:00")!;
  const original = changeOrder(createOrder([], expensive, 1, "expensive", true, today), "DJ-0001", "success");
  const cheaper = searchTrips(conditions, today, original).find(t => t.depart === "07:30")!;
  const refundDifference = quoteReschedule(original, "DJ-0001", cheaper, today);
  assert.equal(refundDifference.deltaCents, -2000);
  assert.equal(submitSimpleReschedule(original, refundDifference, "failed", true, today), original);
  const changed = submitSimpleReschedule(original, refundDifference, "success", true, today);
  assert.equal(submitSimpleReschedule(changed, refundDifference, "success", true, today), changed);
  assert.equal(changed[0].trip.id, cheaper.id);
  assert.deepEqual(paymentLedger(changed[0]), { paidCents: 14800, returnedCents: 2000, netCents: 12800 });
  const samePrice = searchTrips(conditions, today, changed).find(t => t.depart === "13:30")!;
  const raised = quoteReschedule(changed, "DJ-0001", samePrice, today);
  assert.equal(submitSimpleReschedule(changed, refundDifference, "success", true, today), changed);
  assert.throws(() => quoteReschedule(changed, "DJ-0001", cheaper, today));
  assert.equal(raised.deltaCents, 1000);
  const versionChanged = issueInvoice(changed, "DJ-0001", "personal", true);
  assert.throws(() => startPaidReschedule(versionChanged, raised, true, today));
  const refund = quoteRefund(changed[0]);
  assert.equal(refund.amountCents, 12800);
  const refunded = submitRefund(changed, refund, "success", true);
  assert.deepEqual(paymentLedger(refunded[0]), { paidCents: 14800, returnedCents: 13520, netCents: 1280 });
  assert.equal(searchTrips(conditions, today, refunded).find(t => t.id === cheaper.id)?.seats, cheaper.seats);
});
test("zero difference and invoice records are scoped to fare version and order", () => {
  const first = searchTrips(conditions, today).find(t => t.depart === "09:15")!;
  const second = searchTrips(conditions, today).find(t => t.depart === "13:30")!;
  const original = changeOrder(createOrder([], first, 1, "invoice", true, today), "DJ-0001", "success");
  const issued = issueInvoice(original, "DJ-0001", "personal", true);
  assert.equal(activeInvoice(issued[0])?.type, "invoice");
  assert.equal(issueInvoice(issued, "DJ-0001", "personal", true), issued);
  assert.throws(() => issueInvoice(issued, "DJ-0001", "company", true));
  const quote = quoteReschedule(issued, "DJ-0001", second, today);
  assert.equal(quote.deltaCents, 0);
  const changed = submitSimpleReschedule(issued, quote, "success", true, today);
  assert.equal(activeInvoice(changed[0]), null);
  const reissued = issueInvoice(changed, "DJ-0001", "company", true);
  assert.equal(activeInvoice(reissued[0])?.type, "invoice");
  assert.equal(reissued[0].events.filter(e => e.type === "invoice").length, 2);
  const refund = submitRefund(reissued, quoteRefund(reissued[0]), "success", true);
  assert.equal(activeInvoice(refund[0]), null);
  assert.throws(() => issueInvoice(refund, "DJ-0001", "personal", true));
  const another = changeOrder(createOrder(reissued, trip, 1, "other", true, today), "DJ-0002", "success");
  assert.equal(activeInvoice(another[1]), null);
  assert.equal(activeInvoice(another[0])?.type, "invoice");
});
test("journey follows ticketing and advances once in order", () => {
  const pending = createOrder([], trip, 1, "journey", true, today);
  assert.throws(() => advanceJourney(pending, pending[0].id, "boarding"));
  const ticketed = changeOrder(pending, pending[0].id, "success");
  assert.throws(() => advanceJourney(ticketed, ticketed[0].id, "en_route"));
  const boarding = advanceJourney(ticketed, ticketed[0].id, "boarding");
  assert.throws(() => advanceJourney(boarding, boarding[0].id, "upcoming"));
  const departed = advanceJourney(boarding, boarding[0].id, "en_route");
  const arrived = advanceJourney(departed, departed[0].id, "completed");
  assert.equal(arrived[0].journeyStage, "completed");
  assert.throws(() => advanceJourney(arrived, arrived[0].id, "completed"));
  assert.throws(() => quoteRefund(arrived[0]));
});
test("refund quote is bound to order version and releases inventory only once", () => {
  const scarce = searchTrips(conditions, today)[1];
  const pending = createOrder([], scarce, 3, "refund", true, today);
  const ticketed = changeOrder(pending, pending[0].id, "success");
  const quote = quoteRefund(ticketed[0]);
  assert.equal(quote.amountCents, ticketed[0].amount * 100);
  assert.equal(quote.feeCents, Math.round(quote.amountCents / 10));
  assert.equal(quote.refundCents, quote.amountCents - quote.feeCents);
  assert.throws(() => submitRefund(ticketed, quote, "success", false));
  assert.equal(submitRefund(ticketed, quote, "failed", true), ticketed);
  assert.throws(() => submitRefund(ticketed, { ...quote, feeCents: 0 }, "success", true));
  const boarding = advanceJourney(ticketed, ticketed[0].id, "boarding");
  assert.throws(() => submitRefund(boarding, quote, "success", true));
  const refunded = submitRefund(ticketed, quote, "success", true);
  assert.equal(refunded[0].status, "refunded");
  assert.equal(submitRefund(refunded, quote, "success", true), refunded);
  assert.equal(searchTrips(conditions, today, refunded)[1].seats, scarce.seats);
  const repurchased = createOrder(refunded, scarce, 3, "repurchase", true, today);
  assert.equal(repurchased[1].id, "DJ-0002");
  assert.throws(() => createOrder(repurchased, scarce, 1, "excess", true, today));
});
test("confirm, idempotency, new purchase key, inventory and recomputed price", () => {
  assert.throws(() => createOrder([], trip, 1, "one", false, today));
  const first = createOrder([], { ...trip, price: 1 }, 2, "one", true, today);
  assert.equal(first[0].amount, trip.price * 2);
  assert.equal(createOrder(first, trip, 2, "one", true, today), first);
  assert.equal(createOrder(first, trip, 2, "two", true, today).length, 2);
  const scarce = searchTrips(conditions, today)[1];
  assert.throws(() => createOrder([], scarce, 4, "x", true, today));
  const occupied = createOrder([], scarce, 3, "full", true, today);
  assert.throws(() => createOrder(occupied, scarce, 1, "next", true, today));
  assert.throws(() => createOrder([], trip, 0, "bad", true, today));
});
test("unknown requires lookup; ticket failure never pays twice; failure retries same order", () => {
  const orders = createOrder([], trip, 1, "one", true, today);
  assert.equal(paymentLedger(orders[0]).paidCents, 0);
  const pending = changeOrder(orders, orders[0].id, "unknown");
  assert.equal(paymentLedger(pending[0]).paidCents, 0);
  assert.throws(() => changeOrder(pending, pending[0].id, "success"));
  const recovered = changeOrder(pending, pending[0].id, "query");
  assert.equal(recovered[0].status, "ticketed");
  assert.equal(changeOrder(recovered, recovered[0].id, "query"), recovered);
  const failed = changeOrder(orders, orders[0].id, "failed");
  assert.equal(changeOrder(failed, failed[0].id, "success")[0].status, "ticketed");
  const ticket = changeOrder(orders, orders[0].id, "ticketing_failed");
  assert.equal(paymentLedger(ticket[0]).paidCents, trip.price * 100);
  assert.throws(() => changeOrder(ticket, ticket[0].id, "failed"));
  assert.equal(changeOrder(ticket, ticket[0].id, "retry_ticket")[0].status, "ticketed");
  assert.equal(orders[0].status, "pending");
  assert.throws(() => changeOrder([] as Order[], "missing", "success"));
});
test("wire boundary rejects identity, transaction injection, invalid dates and long history", () => {
  assert.ok(requestSchema.safeParse({ message: "明天去三亚", conditions }).success);
  assert.ok(requestSchema.safeParse({ message: "2026-09-15从海口去三亚", conditions }).success);
  for (const message of ["我的手机号 138 0000 0000", "110101199001010000", "2026-09-15 手机138-0000-0000", " "]) assert.equal(requestSchema.safeParse({ message }).success, false);
  assert.equal(requestSchema.safeParse({ message: "去三亚", passenger: { name: "x" } }).success, false);
  assert.equal(requestSchema.safeParse({ message: "去三亚", history: Array(17).fill({ role: "user", content: "hi" }) }).success, false);
  assert.equal(requestSchema.safeParse({ message: "hi", conditions: { date: "2026-02-30" } }).success, false);
  assert.equal(responseSchema.safeParse({ intent: "search_trips", conditions, mode: "live", price: 1 }).success, false);
  assert.equal(responseSchema.safeParse({ intent: "request_refund", conditions, mode: "live", orderId: "DJ-0001" }).success, false);
  assert.equal(responseSchema.safeParse({ intent: "request_reschedule", conditions, mode: "live", deltaCents: 100 }).success, false);
  assert.equal(responseSchema.safeParse({ intent: "request_invoice", conditions, mode: "live", invoiceTitle: "real" }).success, false);
});
