import { anomalyInput, anomalyOutput, type AnomalyInput, type AnomalyOutput } from './schemas/anomaly'; import { resolveDateRange, dateRangeDays } from './dates'; import { dailyRecords } from './query'; import { applyFinancialFilters } from './filters'; import { anomalyRuleConfig } from './config'; import type { FinancialDailyRecord } from './types';
function dayBefore(date:string,days:number){const d=new Date(`${date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()-days);return d.toISOString().slice(0,10);}
function sum(records:FinancialDailyRecord[],field:'salesAmountCents'|'transactionAmountCents'|'refundAmountCents'){return records.reduce((total,r)=>total+r[field],0);}
function inScope(record:FinancialDailyRecord,scope:string,kind:'company'|'channel'){return kind==='company'?record.companyId===scope:`${record.companyId} / ${record.channel}`===scope;}
function severity(deviationRate:number){return Math.abs(deviationRate)>=0.45?'high':Math.abs(deviationRate)>=0.30?'medium':'low';}
export function detectFinancialAnomalies(raw:AnomalyInput):AnomalyOutput{const input=anomalyInput.parse(raw),range=resolveDateRange(input.timeRange),records=applyFinancialFilters(dailyRecords,input.filters,range),rules=input.rules??['SALES_DROP','REFUND_RATE','CHANNEL_DROP'],items:AnomalyOutput['items']=[];const dates=dateRangeDays(range);
  for(const date of dates){
    const currentRecords=records.filter(r=>r.date===date);
    const baselineRecords=applyFinancialFilters(dailyRecords,input.filters,{start:dayBefore(date,7),end:dayBefore(date,1)});
    if(rules.includes('SALES_DROP')) for(const company of ['C001','C002','C003']){const actual=sum(currentRecords.filter(r=>inScope(r,company,'company')),'salesAmountCents');const baseline=sum(baselineRecords.filter(r=>inScope(r,company,'company')),'salesAmountCents')/7;if(baseline>0&&actual<baseline*(1-anomalyRuleConfig.SALES_DROP.dropRate!)){const deviationRate=(actual-baseline)/baseline;items.push({rule:'SALES_DROP',severity:severity(deviationRate),message:`${company} 当日销售额低于近7日基线 ${(Math.abs(deviationRate)*100).toFixed(1)}%`,date,scope:company,valueCents:Math.round(actual),baselineCents:Math.round(baseline),deviationRate});}}
    if(rules.includes('CHANNEL_DROP')) for(const company of ['C001','C002','C003']) for(const channel of ['银联','支付宝','微信支付','宝信'] as const){const scope=`${company} / ${channel}`,actual=sum(currentRecords.filter(r=>inScope(r,scope,'channel')),'transactionAmountCents'),baseline=sum(baselineRecords.filter(r=>inScope(r,scope,'channel')),'transactionAmountCents')/7;if(baseline>0&&actual<baseline*(1-anomalyRuleConfig.CHANNEL_DROP.dropRate!)){const deviationRate=(actual-baseline)/baseline;items.push({rule:'CHANNEL_DROP',severity:severity(deviationRate),message:`${scope} 当日交易额低于近7日基线 ${(Math.abs(deviationRate)*100).toFixed(1)}%`,date,scope,valueCents:Math.round(actual),baselineCents:Math.round(baseline),deviationRate});}}
    if(rules.includes('REFUND_RATE')) for(const company of ['C001','C002','C003']) for(const channel of ['银联','支付宝','微信支付','宝信'] as const){const scoped=currentRecords.filter(r=>r.companyId===company&&r.channel===channel),transaction=sum(scoped,'transactionAmountCents'),refund=sum(scoped,'refundAmountCents'),value=transaction?refund/transaction:0;if(value>anomalyRuleConfig.REFUND_RATE.threshold!){const scope=`${company} / ${channel}`;items.push({rule:'REFUND_RATE',severity:value>=0.08?'high':'medium',message:`${scope} 退款率达到 ${(value*100).toFixed(1)}%，超过 ${(anomalyRuleConfig.REFUND_RATE.threshold!*100).toFixed(0)}%阈值`,date,scope,valueRatio:value,baselineRatio:anomalyRuleConfig.REFUND_RATE.threshold!,deviationRate:value-anomalyRuleConfig.REFUND_RATE.threshold!});}}
  }
  return anomalyOutput.parse({items});
}
