import data from '@/lib/works/finance-assistant/data/reconciliation-data.json';
import { resolveDateRange } from './dates';
import { reconciliationConfig } from './config';
import { reconciliationDataSchema, reconcileInput, type ChannelSettlementRecord, type InternalLedgerRecord, type ReconcileInput, type ReconciliationConfig, type ReconciliationData, type ReconciliationGroup, type ReconciliationSummary } from './schemas/reconciliation';

export const toCents=(amount:number)=>Math.round(amount*100);
export const centsEqual=(aCents:number,bCents:number,toleranceCents=reconciliationConfig.amountToleranceCents)=>Math.abs(aCents-bCents)<=toleranceCents;
export function reconcileStepOrder(){return ['EXACT_ONE_TO_ONE','FEE_ADJUSTED_ONE_TO_ONE','TOLERANCE_ONE_TO_ONE','ONE_TO_MANY','MANY_TO_ONE','RESTRICTED_MANY_TO_MANY','CLASSIFY_REMAINDER'] as const;}

type AnyRecord=InternalLedgerRecord|ChannelSettlementRecord;
type Candidate={internal:InternalLedgerRecord[];settlement:ChannelSettlementRecord[];differenceCents:number;feeAdjustmentCents:number;reasonCode:ReconciliationGroup['reasonCode']};
const abs=(value:number)=>Math.abs(value);
const dateValue=(date:string)=>new Date(`${date}T00:00:00Z`).getTime();
const dateDiffDays=(left:string,right:string)=>Math.round(abs(dateValue(left)-dateValue(right))/86400000);
const idSort=(a:AnyRecord,b:AnyRecord)=>a.id.localeCompare(b.id);
const amountTotal=(records:Array<{amountCents:number}>)=>records.reduce((total,record)=>total+record.amountCents,0); const feeTotal=(records:Array<{feeCents:number}>)=>records.reduce((total,record)=>total+record.feeCents,0);
const statusEquivalent=(internal:InternalLedgerRecord,settlement:ChannelSettlementRecord)=>((internal.status==='posted'&&settlement.status==='settled')||(internal.status==='refunded'&&settlement.status==='refunded')||(internal.status==='reversed'&&settlement.status==='pending'));
const identifiersMatch=(internal:InternalLedgerRecord,settlement:ChannelSettlementRecord)=>internal.orderId===settlement.orderId||internal.paymentTxnId===settlement.externalTxnId||internal.paymentTxnId===settlement.paymentTxnId;
const sameCandidateGroup=(internal:AnyRecord,settlement:AnyRecord)=>internal.companyId===settlement.companyId&&internal.channel===settlement.channel&&internal.batchId===settlement.batchId&&dateDiffDays(internal.date,settlement.date)<=reconciliationConfig.maxDateDifferenceDays;
const keyFor=(record:AnyRecord)=>`${record.companyId}|${record.channel}|${record.batchId}`; const dateSpan=(records:AnyRecord[])=>{const dates=records.map(item=>dateValue(item.date));return dates.length?(Math.max(...dates)-Math.min(...dates))/86400000:0};
const sorted=<T extends AnyRecord>(records:T[]):T[]=>[...records].sort(idSort);

function combinations<T extends AnyRecord>(records:T[],minSize:number,maxSize:number){const output:T[][]=[];const sortedRecords=[...records].sort(idSort);function visit(start:number,chosen:T[]){if(chosen.length>=minSize)output.push([...chosen]);if(chosen.length===maxSize)return;for(let index=start;index<sortedRecords.length;index++)visit(index+1,[...chosen,sortedRecords[index]]);}visit(0,[]);return output;}
function bestSumCandidate(internal:InternalLedgerRecord[], settlement:ChannelSettlementRecord[], maxSize:number, config:ReconciliationConfig){
  const target=amountTotal(internal);
  const options=combinations<ChannelSettlementRecord>(settlement,2,maxSize).map((records:ChannelSettlementRecord[])=>({records,difference:target-amountTotal(records)})).filter(option=>abs(option.difference)<=config.amountToleranceCents);
  options.sort((left,right)=>left.records.length-right.records.length||abs(left.difference)-abs(right.difference)||dateSpan(left.records)-dateSpan(right.records)||left.records.map(item=>item.id).join().localeCompare(right.records.map(item=>item.id).join()));
  return options[0];
}
function bestInternalCandidate(internal:InternalLedgerRecord[], settlement:ChannelSettlementRecord, maxSize:number, config:ReconciliationConfig){
  const target=settlement.amountCents;
  const options=combinations<InternalLedgerRecord>(internal,2,maxSize).map((records:InternalLedgerRecord[])=>({records,difference:amountTotal(records)-target})).filter(option=>abs(option.difference)<=config.amountToleranceCents);
  options.sort((left,right)=>left.records.length-right.records.length||abs(left.difference)-abs(right.difference)||dateSpan(left.records)-dateSpan(right.records)||left.records.map(item=>item.id).join().localeCompare(right.records.map(item=>item.id).join()));
  return options[0];
}
function bestManyCandidate(internal:InternalLedgerRecord[], settlement:ChannelSettlementRecord[], maxSize:number, config:ReconciliationConfig){
  const options:Candidate[]=[];
  const internalOptions:InternalLedgerRecord[][]=combinations<InternalLedgerRecord>(internal,2,maxSize);
  const settlementOptions:ChannelSettlementRecord[][]=combinations<ChannelSettlementRecord>(settlement,2,maxSize);
  for(const left of internalOptions) for(const right of settlementOptions){
    const difference=amountTotal(left)-amountTotal(right);
    if(abs(difference)<=config.amountToleranceCents) options.push({internal:left,settlement:right,differenceCents:difference,feeAdjustmentCents:0,reasonCode:difference===0?'SUM_MATCH':'SUM_WITHIN_TOLERANCE'});
  }
  options.sort((left,right)=>left.internal.length+left.settlement.length-right.internal.length-right.settlement.length||abs(left.differenceCents)-abs(right.differenceCents)||dateSpan([...left.internal,...left.settlement])-dateSpan([...right.internal,...right.settlement])||`${left.internal.map(item=>item.id).join()}|${left.settlement.map(item=>item.id).join()}`.localeCompare(`${right.internal.map(item=>item.id).join()}|${right.settlement.map(item=>item.id).join()}`));
  return options[0];
}

function createGroup(id:number,candidate:Candidate,matchType:ReconciliationGroup['matchType'],config:ReconciliationConfig,issueType:ReconciliationGroup['issueType']=null,reasonCode:ReconciliationGroup['reasonCode']=candidate.reasonCode,needsManualReview=false):ReconciliationGroup{const internal=sorted(candidate.internal) as InternalLedgerRecord[];const settlement=sorted(candidate.settlement) as ChannelSettlementRecord[];const dates=[...internal.map(item=>item.date),...settlement.map(item=>item.date)].sort();const internalAmountCents=amountTotal(internal);const settlementAmountCents=amountTotal(settlement);const internalFeeCents=feeTotal(internal);const settlementFeeCents=feeTotal(settlement);const feeAdjustmentCents=candidate.feeAdjustmentCents;const differenceCents=internalAmountCents-settlementAmountCents-feeAdjustmentCents;return {reconciliationId:`RG-${String(id).padStart(4,'0')}`,matchStatus:issueType?'UNMATCHED':'MATCHED',matchType,issueType,companyId:internal[0]?.companyId??settlement[0].companyId,channel:internal[0]?.channel??settlement[0].channel,batchId:internal[0]?.batchId??settlement[0].batchId,dateRange:{start:dates[0],end:dates.at(-1)!},internalIds:internal.map(item=>item.id),settlementIds:settlement.map(item=>item.id),orderIds:[...new Set([...internal.map(item=>item.orderId),...settlement.map(item=>item.orderId)])].sort(),paymentTxnIds:internal.map(item=>item.paymentTxnId).sort(),externalTxnIds:settlement.map(item=>item.externalTxnId).sort(),internalAmountCents,settlementAmountCents,internalFeeCents,settlementFeeCents,feeAdjustmentCents,differenceCents,reasonCode,needsManualReview:needsManualReview||Boolean(issueType&&issueType!=='AMOUNT_MISMATCH')};}
function groupRecordsByKey(internal:InternalLedgerRecord[],settlement:ChannelSettlementRecord[]){const keys=new Set([...internal.map(keyFor),...settlement.map(keyFor)]);return [...keys].sort().map(key=>({internal:internal.filter(item=>keyFor(item)===key).sort(idSort),settlement:settlement.filter(item=>keyFor(item)===key).sort(idSort)}));}
function duplicateSettlementIds(records:ChannelSettlementRecord[]){const occurrences=new Map<string,ChannelSettlementRecord[]>();for(const record of records){const keys=[`external:${record.externalTxnId}`,`order:${record.orderId}|${record.amountCents}|${record.batchId}`];for(const key of keys)occurrences.set(key,[...(occurrences.get(key)??[]),record]);}const duplicateIds=new Set<string>();for(const recordsForKey of occurrences.values())if(recordsForKey.length>1)recordsForKey.forEach(record=>duplicateIds.add(record.id));return duplicateIds;}

export function reconcileTransactions(internal:InternalLedgerRecord[],settlement:ChannelSettlementRecord[],config:ReconciliationConfig=reconciliationConfig):ReconciliationGroup[]{const remainingInternal=new Map(internal.map(item=>[item.id,item]));const remainingSettlement=new Map(settlement.map(item=>[item.id,item]));const groups:ReconciliationGroup[]=[];let groupNumber=1;const takeInternal=(items:InternalLedgerRecord[])=>items.forEach(item=>remainingInternal.delete(item.id));const takeSettlement=(items:ChannelSettlementRecord[])=>items.forEach(item=>remainingSettlement.delete(item.id));const push=(candidate:Candidate,type:ReconciliationGroup['matchType'],issue:ReconciliationGroup['issueType']=null,reason:ReconciliationGroup['reasonCode']=candidate.reasonCode,manual=false)=>{groups.push(createGroup(groupNumber++,candidate,type,config,issue,reason,manual));takeInternal(candidate.internal);takeSettlement(candidate.settlement);};
  // Step 1-3: only traceable identifiers can enter one-to-one matching.
  for(const internalRecord of sorted([...remainingInternal.values()]) as InternalLedgerRecord[]){const candidates=(sorted([...remainingSettlement.values()]) as ChannelSettlementRecord[]).filter(settlementRecord=>sameCandidateGroup(internalRecord,settlementRecord)&&identifiersMatch(internalRecord,settlementRecord));const exact=candidates.find(item=>item.amountCents===internalRecord.amountCents);if(exact){const issue=statusEquivalent(internalRecord,exact)?null:'STATUS_MISMATCH';push({internal:[internalRecord],settlement:[exact],differenceCents:0,feeAdjustmentCents:0,reasonCode:'EXACT'},'ONE_TO_ONE',issue,issue?'STATUS_DIFFERENCE':'EXACT',Boolean(issue));continue;}const fee=candidates.find(item=>internalRecord.amountCents-internalRecord.feeCents===item.amountCents&&internalRecord.feeCents>0);if(fee){const issue=statusEquivalent(internalRecord,fee)?null:'STATUS_MISMATCH';push({internal:[internalRecord],settlement:[fee],differenceCents:0,feeAdjustmentCents:internalRecord.feeCents,reasonCode:'FEE_ADJUSTED'},'ONE_TO_ONE',issue,issue?'STATUS_DIFFERENCE':'FEE_ADJUSTED',Boolean(issue));continue;}const tolerance=candidates.find(item=>centsEqual(internalRecord.amountCents,item.amountCents,config.amountToleranceCents));if(tolerance){const issue=statusEquivalent(internalRecord,tolerance)?null:'STATUS_MISMATCH';push({internal:[internalRecord],settlement:[tolerance],differenceCents:internalRecord.amountCents-tolerance.amountCents,feeAdjustmentCents:0,reasonCode:'WITHIN_TOLERANCE'},'ONE_TO_ONE',issue,issue?'STATUS_DIFFERENCE':'WITHIN_TOLERANCE',Boolean(issue));}}
  // Step 4: one internal to a bounded settlement subset.
  for(const internalRecord of sorted([...remainingInternal.values()]) as InternalLedgerRecord[]){const candidates=(sorted([...remainingSettlement.values()]) as ChannelSettlementRecord[]).filter(item=>sameCandidateGroup(internalRecord,item));if(candidates.length>config.maxRecordsPerSide)continue;const option=bestSumCandidate([internalRecord],candidates,config.maxRecordsPerSide,config);if(option)push({internal:[internalRecord],settlement:option.records,differenceCents:option.difference,feeAdjustmentCents:0,reasonCode:option.difference===0?'SUM_MATCH':'SUM_WITHIN_TOLERANCE'},'ONE_TO_MANY');}
  // Step 5: bounded internal subset to one settlement.
  for(const settlementRecord of sorted([...remainingSettlement.values()]) as ChannelSettlementRecord[]){const candidates=(sorted([...remainingInternal.values()]) as InternalLedgerRecord[]).filter(item=>sameCandidateGroup(item,settlementRecord));if(candidates.length>config.maxRecordsPerSide)continue;const option=bestInternalCandidate(candidates,settlementRecord,config.maxRecordsPerSide,config);if(option)push({internal:option.records,settlement:[settlementRecord],differenceCents:option.difference,feeAdjustmentCents:0,reasonCode:option.difference===0?'SUM_MATCH':'SUM_WITHIN_TOLERANCE'},'MANY_TO_ONE');}
  // Step 6-7: candidate-group bounded N:M, then deterministic classification.
  const duplicateIds=duplicateSettlementIds(settlement);for(const candidateGroup of groupRecordsByKey([...remainingInternal.values()], [...remainingSettlement.values()])){let currentInternal=candidateGroup.internal.filter(item=>remainingInternal.has(item.id));let currentSettlement=candidateGroup.settlement.filter(item=>remainingSettlement.has(item.id));if(!currentInternal.length&&!currentSettlement.length)continue;if(currentInternal.length>config.maxRecordsPerSide||currentSettlement.length>config.maxRecordsPerSide){push({internal:currentInternal,settlement:currentSettlement,differenceCents:amountTotal(currentInternal)-amountTotal(currentSettlement),feeAdjustmentCents:0,reasonCode:'SEARCH_LIMIT_EXCEEDED'},'UNMATCHED','MANUAL_REVIEW_REQUIRED','SEARCH_LIMIT_EXCEEDED',true);continue;}const many=bestManyCandidate(currentInternal,currentSettlement,config.maxRecordsPerSide,config);if(many)push(many,'MANY_TO_MANY');currentInternal=currentInternal.filter(item=>remainingInternal.has(item.id));currentSettlement=currentSettlement.filter(item=>remainingSettlement.has(item.id));for(const item of currentInternal){const candidates=currentSettlement.filter(other=>identifiersMatch(item,other));const candidate=candidates[0];if(candidate){const issue=item.amountCents===candidate.amountCents?(statusEquivalent(item,candidate)?'AMOUNT_MISMATCH':'STATUS_MISMATCH'):'AMOUNT_MISMATCH';const reason=issue==='STATUS_MISMATCH'?'STATUS_DIFFERENCE':(item.status==='refunded'||candidate.status==='refunded'?'REFUND_AMOUNT_DIFFERENCE':'AMOUNT_DIFFERENCE');push({internal:[item],settlement:[candidate],differenceCents:item.amountCents-candidate.amountCents,feeAdjustmentCents:0,reasonCode:reason as ReconciliationGroup['reasonCode']},'ONE_TO_ONE',issue,reason as ReconciliationGroup['reasonCode'],issue==='STATUS_MISMATCH');continue;}push({internal:[item],settlement:[],differenceCents:item.amountCents,feeAdjustmentCents:0,reasonCode:'NO_SETTLEMENT'},'UNMATCHED','INTERNAL_ONLY','NO_SETTLEMENT');}currentSettlement=currentSettlement.filter(item=>remainingSettlement.has(item.id));for(const item of currentSettlement){const issue=duplicateIds.has(item.id)?'DUPLICATE_SUSPECTED':'CHANNEL_ONLY';push({internal:[],settlement:[item],differenceCents:-item.amountCents,feeAdjustmentCents:0,reasonCode:issue==='DUPLICATE_SUSPECTED'?'DUPLICATE_KEY':'NO_INTERNAL'},'UNMATCHED',issue,issue==='DUPLICATE_SUSPECTED'?'DUPLICATE_KEY':'NO_INTERNAL',issue==='DUPLICATE_SUSPECTED');}}
  // Defensive invariant: malformed input still receives deterministic single-side groups.
  for(const item of sorted([...remainingInternal.values()]) as InternalLedgerRecord[])push({internal:[item],settlement:[],differenceCents:item.amountCents,feeAdjustmentCents:0,reasonCode:'NO_SETTLEMENT'},'UNMATCHED','INTERNAL_ONLY','NO_SETTLEMENT');for(const item of sorted([...remainingSettlement.values()]) as ChannelSettlementRecord[])push({internal:[],settlement:[item],differenceCents:-item.amountCents,feeAdjustmentCents:0,reasonCode:'NO_INTERNAL'},'UNMATCHED','CHANNEL_ONLY','NO_INTERNAL');return groups;}

export function summarizeReconciliation(groups:ReconciliationGroup[],internal:InternalLedgerRecord[],settlement:ChannelSettlementRecord[]):ReconciliationSummary{const matched=groups.filter(group=>group.matchStatus==='MATCHED');const unmatched=groups.filter(group=>group.matchStatus==='UNMATCHED');const matchedInternalIds=new Set(matched.flatMap(group=>group.internalIds));const matchedSettlementIds=new Set(matched.flatMap(group=>group.settlementIds));const count=(type:ReconciliationGroup['matchType'])=>matched.filter(group=>group.matchType===type).length;const issue=(type:NonNullable<ReconciliationGroup['issueType']>)=>groups.filter(group=>group.issueType===type).length;const totalInternalAmountCents=amountTotal(internal);const totalSettlementAmountCents=amountTotal(settlement);const matchedAmountCents=matched.reduce((total,group)=>total+group.internalAmountCents,0);return {totalInternalCount:internal.length,totalSettlementCount:settlement.length,totalInternalAmountCents,totalSettlementAmountCents,matchedInternalCount:matchedInternalIds.size,matchedSettlementCount:matchedSettlementIds.size,matchedCounts:{oneToOne:count('ONE_TO_ONE'),oneToMany:count('ONE_TO_MANY'),manyToOne:count('MANY_TO_ONE'),manyToMany:count('MANY_TO_MANY')},issueCounts:{amountMismatch:issue('AMOUNT_MISMATCH'),internalOnly:issue('INTERNAL_ONLY'),channelOnly:issue('CHANNEL_ONLY'),statusMismatch:issue('STATUS_MISMATCH'),duplicateSuspected:issue('DUPLICATE_SUSPECTED'),manualReviewRequired:issue('MANUAL_REVIEW_REQUIRED')},matchedAmountCents,unmatchedAmountCents:unmatched.reduce((total,group)=>total+group.internalAmountCents,0),unmatchedSettlementAmountCents:unmatched.reduce((total,group)=>total+group.settlementAmountCents,0),recordMatchRate:internal.length?matchedInternalIds.size/internal.length:null,amountMatchRate:totalInternalAmountCents?matchedAmountCents/totalInternalAmountCents:null,groupsCount:groups.length};}

export function loadReconciliationData():ReconciliationData{return reconciliationDataSchema.parse(data);}
export function reconcileFromData(input:ReconcileInput){const parsed=reconcileInput.parse(input);const range=resolveDateRange(parsed.timeRange);const source=loadReconciliationData();const filter=(record:AnyRecord)=>record.date>=range.start&&record.date<=range.end&&(!parsed.channel||record.channel===parsed.channel)&&(!parsed.companyId||record.companyId===parsed.companyId)&&(!parsed.companyIds||parsed.companyIds.includes(record.companyId));const internal=source.internalLedger.filter(filter);const settlement=source.channelSettlement.filter(filter);const groups=reconcileTransactions(internal,settlement);if(parsed.mode==='summary')return {mode:'summary' as const,summary:summarizeReconciliation(groups,internal,settlement)};const filtered=groups.filter(group=>(!parsed.issueType||group.issueType===parsed.issueType)&&(!parsed.matchType||group.matchType===parsed.matchType));const sortBy=parsed.sortBy??'ABS_DIFFERENCE_DESC';const limit=parsed.limit??20;const sortedGroups=[...filtered].sort((left,right)=>{if(sortBy==='ID_ASC')return left.reconciliationId.localeCompare(right.reconciliationId);if(sortBy==='DATE_DESC')return right.dateRange.end.localeCompare(left.dateRange.end)||left.reconciliationId.localeCompare(right.reconciliationId);return Math.abs(right.differenceCents)-Math.abs(left.differenceCents)||left.reconciliationId.localeCompare(right.reconciliationId);});return {mode:'details' as const,groups:sortedGroups.slice(0,limit)};}
