/* eslint-disable @typescript-eslint/no-explicit-any */
import { calculateSubsidy, checkMaterialCompleteness, queryDocuments, queryPerformance, queryPolicyRules, queryProject, queryRegulatoryStats, verifyProjectData } from "../tools";
import type { ToolName } from "../types";

export type ChatMessage={role:"user"|"assistant";content:string};
export type AgentResponse={answer:string;usedTools:ToolName[];blocks:Array<{type:string;title:string;data:unknown}>};

function run(name:ToolName,input:unknown,blocks:AgentResponse["blocks"],usedTools:ToolName[]){const data={query_project:queryProject,query_documents:queryDocuments,check_material_completeness:checkMaterialCompleteness,query_policy_rules:queryPolicyRules,verify_project_data:verifyProjectData,calculate_subsidy:calculateSubsidy,query_performance:queryPerformance,query_regulatory_stats:queryRegulatoryStats}[name](input);usedTools.push(name);blocks.push({type:name,title:{query_project:"项目概览",query_documents:"申报材料",check_material_completeness:"材料完整性",query_policy_rules:"政策依据",verify_project_data:"数据核验",calculate_subsidy:"补贴测算",query_performance:"绩效跟踪",query_regulatory_stats:"监管统计"}[name],data});return data as any;}

export function answerMessage(message:string,projectId?:string,conversationHistory:ChatMessage[]=[]):AgentResponse{
  const text=message.trim(); const blocks:AgentResponse["blocks"]=[]; const usedTools:ToolName[]=[]; const context=conversationHistory.map(item=>item.content).join(" "); const pid=projectId ?? (text.match(/PRJ-[A-I]/i)?.[0].toUpperCase() ?? context.match(/PRJ-[A-I]/i)?.[0].toUpperCase() ?? (text.includes("产业数字化")||context.includes("产业数字化")?"PRJ-A":text.includes("智能生产线")||context.includes("智能生产线")?"PRJ-B":text.includes("产业服务平台")||context.includes("产业服务平台")?"PRJ-C":text.includes("数据中台")||context.includes("数据中台")?"PRJ-G":""));
  if(text.includes("简报")){const s=run("query_regulatory_stats",{},blocks,usedTools);const p=run("query_performance",{projectId:"PRJ-C"},blocks,usedTools);return {answer:"当前监管简报：共 "+s.projectCount+" 个项目，风险项目共 "+s.riskProjectIds.length+" 个（"+s.riskProjectIds.join("、")+"），申请补贴合计 "+(s.requestedSubsidyTotal/10000)+" 万元，核定补贴合计 "+(s.approvedSubsidyTotal/10000)+" 万元，已拨付 "+(s.paidSubsidyTotal/10000)+" 万元。绩效方面，PRJ-C 业务服务量完成率为 "+(p.metrics.find((m:any)=>m.metric.includes("业务"))?.completionRate*100)+"%，属于重点关注项目。",usedTools,blocks};}
  if(text.includes("统计")||text.includes("多少项目")||text.includes("总体")||text.includes("拨付了多少")){const s=run("query_regulatory_stats",{},blocks,usedTools);return {answer:"当前共有 "+s.projectCount+" 个项目，申请补贴合计 "+(s.requestedSubsidyTotal/10000)+" 万元，核定补贴合计 "+(s.approvedSubsidyTotal/10000)+" 万元，已拨付 "+(s.paidSubsidyTotal/10000)+" 万元。风险项目共 "+s.riskProjectIds.length+" 个，包括 "+s.riskProjectIds.join("、")+"。",usedTools,blocks};}
  if(text.includes("200 万")||text.includes("200万")||text.includes("最多能拿")||text.includes("最多可以补贴")||text.includes("最多补贴")){const investment=pid==="PRJ-A"?2180000:2000000; const s=run("calculate_subsidy",{approvedInvestment:investment},blocks,usedTools);return {answer:"按 30% 比例，"+(investment/10000)+" 万元核定投资的理论补贴为 "+(s.theoreticalSubsidy/10000)+" 万元；但受 P-005 单项目 50 万元上限约束，最终可补贴 "+(s.finalSubsidy/10000)+" 万元。",usedTools,blocks};}
  if(pid==="PRJ-A"){run("query_project",{projectId:pid},blocks,usedTools);run("check_material_completeness",{projectId:pid},blocks,usedTools);run("verify_project_data",{projectId:pid},blocks,usedTools);run("query_policy_rules",{ruleId:"P-003"},blocks,usedTools);run("query_policy_rules",{ruleId:"P-005"},blocks,usedTools);run("calculate_subsidy",{approvedInvestment:2180000},blocks,usedTools);return {answer:"企业主体经营时间及经营状态符合基本申报要求，但当前项目不宜直接通过：缺少项目验收证明；申请书投资额 268 万元与合同金额 218 万元相差 50 万元，发票合计 216 万元与申报投资额相差 52 万元；按合同金额测算理论补贴 65.4 万元，但 P-005 将单项目上限限定为 50 万元，申请的 68 万元超过上限。建议补充验收证明、说明金额差异并重新审核。",usedTools,blocks};}
  if(pid==="PRJ-B" || text.includes("业务量") || text.includes("利用率") || text.includes("运行时间")){const bid=pid||"PRJ-B";run("query_project",{projectId:bid},blocks,usedTools);run("verify_project_data",{projectId:bid},blocks,usedTools);return {answer:"项目材料、合同和资金材料暂未发现明显异常，但跨数据源核验发现：申报运行 6 个月、系统有效运行约 4 个月；申报业务量 12,800 次，实际 8,460 次，相差 4,340 次，申报量较实际高约 51%；申报利用率 81%，系统记录为 58%，相差 23 个百分点。当前数据存在明显一致性疑点，建议进一步核实统计口径，不直接判断为数据造假。",usedTools,blocks};}
  if(pid==="PRJ-C" || text.includes("全部使用") || text.includes("拿到钱")){const cid=pid||"PRJ-C";run("query_project",{projectId:cid},blocks,usedTools);run("query_performance",{projectId:cid},blocks,usedTools);return {answer:"该项目资金已全部拨付，资金执行率为 100%；但年度业务服务量完成率仅 42%，服务企业数量完成约 56%，月均活跃率为 39%，低于 70%目标。根据 P-008，应列为重点关注项目，继续了解运营不足及目标差异原因。",usedTools,blocks};}
  if(pid==="PRJ-G" || text.includes("疑似重复")){const gid=pid||"PRJ-G";run("query_project",{projectId:gid},blocks,usedTools);run("query_policy_rules",{ruleId:"P-006"},blocks,usedTools);return {answer:"PRJ-G 企业数据中台建设项目与历史项目 PRJ-G-OLD《企业数据平台建设项目》高度相似，且企业 G 上一年度已有同类资金支持记录，因此标记为疑似重复申报，仍需人工复核，不能直接认定为重复申报。",usedTools,blocks};}
  if(pid==="PRJ-I"||text.includes("绩效最好")){run("query_performance",{projectId:"PRJ-I"},blocks,usedTools);return {answer:"PRJ-I 供应链协同平台项目绩效表现最好，年度业务服务量完成 11,600 次，完成率为 116%，状态为绩效完成。",usedTools,blocks};}
  if(text.includes("效果不好")||text.includes("绩效异常")){run("query_regulatory_stats",{},blocks,usedTools);run("query_performance",{projectId:"PRJ-C"},blocks,usedTools);return {answer:"当前已识别的绩效异常项目为 PRJ-C 产业服务平台建设项目，核心业务服务量完成率为 42%，应重点跟踪。",usedTools,blocks};}
  const s=run("query_regulatory_stats",{},blocks,usedTools);return {answer:"我可以围绕项目材料、政策规则、跨源数据、补贴测算、绩效和监管统计查询。当前有 "+s.projectCount+" 个虚构项目。请指定项目编号或选择推荐问题。",usedTools,blocks};
}
